project: 
  type: website
  output-dir: docs

website: 
  title: "データ分析情報まとめ"
  favicon: favicon_io/favicon.ico
  navbar: 
    left: 
      - href: index.md
        text: Home
  sidebar: 
    contents: auto

format: 
  html: 
    theme: flatly
    toc: true
    lang: ja
    css: _styles/style.css
    bibliography: references.bib
    code-block-bg: true
    code-line-numbers: true
    from: markdown+emoji
  gfm: 
    variant: "+emoji"
    toc: true
    lang: ja


execute: 
  cache: true
  freeze: auto
