# 第1章 思考編

- ゼロベース思考
    - ゼロベースで物事を考える=「既成の枠」を取り外す
- 仮説思考
    - 常にその時点での結論を持ってアクションを起こす

```{mermaid}
%%| fig-cap: ビジネスでは、結果がうまくいかなければバリューはない。
%%| label: fig-1-1
graph LR
A[わかること] -- 大きな溝 --> B[実行できること] -- 大きな溝 --> C[結果がうまくいくこと]
```

ビジネスを成功に導く = 「結果がうまくいく」ための思考がゼロベース思考と仮説思考


## 1 <ゼロベース思考> --- 「既成の枠」を取り外す ---

::: {.message}
<ゼロベース思考>の2つのポイント
:::

- 自分の狭い枠の中で否定に走らない
- 顧客にとっての価値を考える

### 1. 自分の狭い枠の中で否定に走らない

::: {.message}
<ゼロベース思考>の妨げになるのは「既成の枠」  
「この課題を解決するための具体策はある」という前提でゼロベースから考える
:::

- 既存の枠で考える従来どおりの思考
    - 枠の外にある解決策を見落とす
    - 枠の中の否定的要素を列挙してしまう
- ゼロベース思考
    - 自分の狭い枠を超えて考える
    - 解決策を見出す可能性が高まる

### 2. 顧客にとっての価値を考える

::: {.message}
自分の立場だけで問題をとらえるのではなく、
「顧客にとっての価値」を考え、実行に移すことが大事
:::

- 自分の立場だけで問題をとらえると「既成の枠」から抜け出せない
- 多くの創業者がビジネスを立ち上げることに成功した理由は、自身が開発者であるとどう似にユーザーでもあったから
    - このため、「顧客にとっての価値」を考え、貫くことができた
- 大企業になると「顧客にとっての価値」を考え、貫くことができない
    - 規模の拡大により消費者との距離が遠くなるため

#### 事例1 --- 消費者の行動変化を加速させる決断

::: {.message}
ZARAは<ゼロベース思考>を徹底することで、業界の常識を破り、成功した
:::

- 競合他社との違い
    - 徹底的な自前主義
    - 在庫切れを奨励。顧客の来店を促す
    - 承認の約半数を自社工場で製造。
- <ゼロベース思考>の徹底
    - ビジネスシステム全体を<ゼロベース思考>で構想
    - 構想通りのオペレーションを現場で徹底
    - 顧客と製造の間のコミュニケーションがスムーズかつスピーディ

::: {.message}
ドトールは<ゼロベース思考>を用いてコーヒー外飲市場を切り開いた
:::

- ドトールの成功
    - 低価格で美味しいコーヒーを提供
    - 1日数百人もの来店
- <ゼロベース思考>
    - 「喫茶店に1日数百人も入らない」を取り払う
        - 単価を低くすることを実現
    - 「1日に1000杯もフレッシュなコーヒーを瞬時に供給できない」を取り払う
        - 海外の優れたコーヒーマシンを導入

#### 事例2 --- 技術革新を消費者の目でとらえる


##### シャープ

- 液晶=電卓という枠組みを取り払い、液晶そのものをキーデバイス化
- 「オンリーワンを積み重ねてナンバーワンになる」の基本姿勢
- 「環境先進企業」としてのブランド形成

##### ユニクロ・東レ

### 3. 時代が<ゼロベース思考>を求めている




## 2 <仮説思考> --- 常にその時点での結論を持ってアクションを起こす ---

::: {.message}
<仮説思考>の3つのポイント
:::

- アクションに結び付く議論を常に持つ --- 結論の仮説
- 結論に導く背後の理由やメカニズムを考える --- 理由の仮説
- 「ベスト」を考えるよりも「ベター」を実行する --- スピードを重視

### 1 アクションに結び付く議論を常に持つ

::: {.message}
なにがなんでも結論を出すことが仮説思考の始まり  
ビジネスでは1つの具体的結論が100の評論に勝る
:::

- まず結論を出す
- 出した結論に対して SO WHAT? (だから何なの) を繰り返す
- アクションに結び付く結論を出す


最初は的を外していても、常にアクションに結び付く結論を持つをいうことを心がけると精度は上がる。



##### 例1

- 体重が増えた
- SO WHAT?
    - 体重が増えて血圧も上がりやすくなった
    - 痩せないと健康によくない
    - 運動をする
    - スポーツクラブへ週3回行く（具体的なアクションにつながる結論）


### 2 結論に導く背後の理由やメカニズムを考える

```{mermaid}
%%|fig-cap: "「背後のメカニズムの把握」と「アクションに結び付く結論を持つ」は鶏と卵の関係"
%%|label: fig-2-2-1

graph TD
A[背後のメカニズムの把握] -- メカニズムがわかればアクションに結び付く結論が出せる --> B[アクションに結び付く結論を持つ]
B -- アクションに結び付く結論を持てば背後のメカニズムを自然に考えられる --> A
```

- 背後のメカニズムを把握していれば
    - 軌道修正が容易
    - 要と思われるものの裏をとれる

:::{.left-line}
##### 演習例1 --- 家庭用殺虫剤への新規参入の結論を出す

課題：「家庭用ゴキブリ殺虫剤の年間市場を10分以内に推定せよ」

- 方法1: ゴキブリ殺虫剤の市場規模に関する調査資料を探索する
    - 10分以内では困難
    - 成長が始まったばかりで市場データがない場合も困難
- 方法2: 自分で市場規模を推定する
    - 方法1が困難なときはこちらをせざるを得ない場合がある

推定例:  

最も簡単な方法は 市場規模 = 1世帯あたりの年間利用金額 × カバー世帯数 によって推定する方法

- 全国5000万世帯
- 1世帯あたり年間2000円
- **最大 2000 円/世帯 × 5000万世帯 = 1000億円**

全世帯が使用するのは現実的でない  
ファミリー世帯が需要の中心として、ファミリー世帯が占める割合を推定する

- 新聞などで発表される平均世帯数は3人
- 4人家族か1人暮らしかに限定すると、3人 = 4人 × x% + 1人 × (100 - x)% を解いてファミリー世帯は約70%
- 北の地域や新しいマンションでは使用しないとし、使用する世帯はファミリー世帯の半分とすると 70% × 50% = 35%
- 全世帯の約3分の1の 1700世帯 が使用世帯となる

年間使用金額を推定する

- エアゾールタイプは約500円、年間一本と仮定
- ベイト剤タイプは一個50円、6カ月使用、ひと月4個使用と仮定。 50円 × 4個 × 6カ月 = 1200円 
- エアゾールとベイト剤を足して 1700円。約2000円
- 世帯数と金額をかけ合わせて **平均 2000 円/世帯 × 1700万世帯 = 340億円**

現時点でのアクションに結び付く結論:  
**「家庭用ゴキブリ殺虫剤市場は340億円程度の成熟市場で成長の見込みが低く、新規参入を検討するほど市場に魅力がない」**

:::



::: {.message}
その時点での結論を出すこと自体が、後にさらに考えを深め、より良い解決策をだすことに結び付く
:::

- もし根拠が希薄で不安のあるすうじがあれば、そこだけを検証すれば格段に精度が上がるはず
- メカニズムに関する仮説が納得のいくものであるが、実際の数字より多い額が出てしまったとき
    - 仮説が間違っているかもしれない
    - 市場が発展途上の場合は、ポテンシャル市場の額を表しており、企業が十分に市場をカバーしていないとも考えられる

::: {.left-line}
##### 演習例2 --- 自転車市場への新規参入の結論を出す

課題: 「日本国内における自転車の年間市場を推定し、新規参入の是非に関する結論を出しなさい」  


推定例:

自転車に乗る人は小学生から60歳までと仮定。
平均寿命80歳、各年齢の人口が同じ数だとすると、自転車に乗る人は大体 50/80 くらい。
全人口が1億3000万人。 1人1台とする。

1億3000万人 × 5/8 = 8125万人

6年に1回買い替えると予想

市場規模 8125万人 × 1回/6年 = 1350万台

平均価格を1万5000円とすると

1.5万円 × 1350万台 = 2025億円


現時点での結論:

**「自転車市場は市場性を評価すると新規参入を検討する価値は十分にある。それに当たっては電動アシスト自転車の普及版も視野に入れた市場を考えるべきである」**

別の推定例:

年代別の購入・買い替え頻度

- 幼稚園児から小学生(3~12歳): 3年で買い替え
- 中学生から大学生(13~22歳): 5年買い替え
- 社会人(23~60歳): 10年で買い替え
- 高齢者(61~80歳): 買い替えをしない

年代別の人口分布が均一、平均寿命を80歳とする。
それぞれの年代の人数に1年以内に購入する確率をかけたものを足し上げる

{ (10 × 1/3 ) + ( 10 × 1/5 ) + (38 × 1/10) + (20 × 0) } × ( 1億3000万 ÷ 80 ) = 1480万台

市場規模 1.5万円 × 1480万台 = 2220億円

現時点での結論:

**「自転車市場は市場性を評価すると新規参入を検討する価値は十分にある。自転車市場を細分化し、高付加価値セグメンテーションをメインターゲットに市場参入すべきである」**
:::

- 推定した数字が違っていることがわかっても、そこの数字だけを調べて計算しなおす
    - ゼロから調べるよりも効率的
- 一応出した結論に基づいてアクションプランを立て、同時に裏を取ることができる（分析とアクションの同時並行）

### 3 「ベスト」を考えるよりも「ベター」を実行する

::: {.message}
実行することにより、今よりもベターな状況が想定されれば、とにかく実行に移す
:::

- ビジネスでは絶対的な正解はない
- ベターな解決策を見つけたらすぐに実行する
- どんどん軌道修正していく

::: {.message}
ベターな解決策で現場を動かすほうが効率的
:::

- ベターな解決策でも現場を動かし始めると精度の高いすぐ役立つ情報が自動的に入ってくる
- ベターな解決策が見えたらすぐに実行に移し、試行錯誤を重ねる
- ベストは最後に見えてくる




```{mermaid}
graph LR
subgraph 最初の段階
    A1[現時点での結論] --> B1[検証]
    B1 --> C1[実行]
end
subgraph 次の段階
    A2[現時点での結論] --> B2[検証]
    B2 --> C2[実行]
end
subgraph その次の段階
    A3[現時点での結論] --> B3[検証]
    B3 --> C3[実行]
end

C1 --> A2 
C2 --> A3 
C3 --> D[究極の解]
```

#### 情報収集に時間を使いすぎない

- ビジネスの現場では、時間と環境の変化にしたがって解決策が変化していく
- 6割レベルの情報が集まったら一度方向性の判断を行う

::: {.message}
初めにアクションに結び付く結論を言い、その結論に導く理由を説明する
:::

