# 第2章 技術編

- 第1章の2つの思考は問題解決のための基本態度
- 第2章の2つの技術は問題解決のための基本スキル

## ＜MECE＞ ＜ロジックツリー＞ を応用する

### 市場/競合/自社のとらえ方に大きなモレはないか

- 戦略を考えるうえで3つの動きを「モレ」なくカバーすることの大切さ
- 戦略を実行するうえで「広がり」を押さえ「具体化」することの重要さ

をスーパードライの誕生の背景を追いながら考える

::: {.left-line}


#### 市場（顧客）

- 一般的な見方:
    - 値上げや嗜好の多様化によりビール市場は成熟してしまった
- 消費者レベルで掘り下げた見方:
    - 「生化」や「缶化」といった構造的変化はすでに進行していた
    - 従来の生ビールでは十分に満足できない「ドライな生」を求めるニーズ浮上しようとしていた

#### 競合

- スーパードライの出現前の競合の状況:
    - ビール業界は「成熟市場」だという「既成の枠」にはまり込む
    - 「味」からかけ離れたところで競争が繰り広げられる
- 消費者にとってはただ騒々しいだけ
- 当時のアサヒビールもその慣習に追随していただけだった

#### 自社

- アサヒビールのシェアは下落
- コスト削減のため二流の原材料を使用
- 在庫がダブつき、日付の古いおいしくないビールが店頭にならぶ
\
:::


```{mermaid}
%%| fig-cap: "スーパードライの「フレッシュ・ローテーション」革命"
%%| label: fig-1-1-1
graph TB
subgraph 過去の悪循環
    A[店頭での日付が古い] --> B[飲んでもおいしくない]
    B --> C[次から買わない]
    C --> D[流通がダブつく]
    D --> A
end
subgraph 現在の良循環
    A2[店頭での日付が新しくフレッシュ] --> B2[飲めば新鮮でおいしい]
    B2 --> C2[また次に買う]
    C2 --> D2[流通がダブつかない]
    D2 --> A2
end
```


::: {.message}
戦略は消費者が支配する\
市場(顧客)への深い洞察から新たなビジネスの種は生まれる
:::


- 新たなコンセプトの生ビールで、大きな消費者の「モレ」をとらえた
- 日本のビールを「保存」飲料から「生鮮」飲料に変えた

\

- 企業経営においては競合の動きや自社の業績が目に入りやすい
- 一番遠く見落としがちなのが、市場の動き
- 市場の動きをとらえ、「顧客にとっての価値」を考えることを忘れない

### 計画は緻密に具体化し、実践は徹底する

- アサヒビールのスーパードライ戦略の基本:
    - 「おいしいビールを消費者に提供する」
- そのための3つの要件
    - 「いいものを作る」
    - 「いいものを伝える」
    - 「いいものを維持する」

```{mermaid}
%%| fig-cap: "スーパードライの戦略展開"
%%| label: fig-1-1-2
graph LR
A[おいしい生ビールを消費者に提供する]

B1[いいものを作る]
B2[いいものを伝える]
B3[いいものを維持する]

subgraph 主要な打ち手
C11["消費者の求める「軽くてのど越しがいいドライ」な生ビールを開発する"]
C12["最高の原材料を使って品質が最高のビールを生産する"]

C21["100万人の消費者に135mlの試飲缶をトライしてもらうイベント・キャンペーンを実施"]
C22["TV-CMを中心とした大々的広告キャンペーンを実施する"]
C23["酒販店にフレッシュ・ローテーションを徹底して伝えるインナー・キャンペーンを実施する"]

C31["工場出荷から8日以内に店頭に並べ、<br>
3カ月経ったものは店頭に置かないフレッシュ・ローテーションを徹底する"]
C32["マーケットレディーを組織化し、<br>
酒販店からの商品クレームや売り上げ情報を本社にフィードバックする"]
end

A --> B1
A --> B2
A --> B3

B1 --> C11
B1 --> C12

B2 --> C21
B2 --> C22
B2 --> C23

B3 --> C31
B3 --> C32
```

## 1 ＜MECE＞ --- モレはないかダブりはないかをチェックする ---

Mutually Exclusive Collectively Exhaustive

### 1 ＜MECE＞をビジネスで使いこなす

＜MECE＞が重要な理由は、経営資源に制限がある限り、大きなモレやダブりは
ビジネスの効果・効率を著しく阻害するため。

＜MECE＞を活用する上での3つのポイント

- **モレ**によって的を外していないか？
- **ダブり**によって効率を阻害していないか？
- **＜MECE＞**でとらえ、最後に**優先順位**をつけているか？

#### モレによって的を外していないか？

できるだけモレを出さないように、
<ゼロベース思考>で物事を大きくとらえることから始めるべき。

#### ダブりによって効率を阻害していないか

ダブりが生じていると、
資源配分上効率が悪くなるだけでなく、
受け手に対して混乱を与える場合がある。

#### ＜MECE＞でとらえ、最後に優先順位をつけているか？

::: {.message}
＜MECE＞でとらえられるようになったら、
必ず優先順位をつける。\
どんなに＜MECE＞になっていても、すべてをカバーした網羅的な解決策は、
何も言っていないのと同じことである。
:::

特に＜MECE＞の重要性が増すのは、
戦略を立案するとき。
貴重な経営資源の配分に当たっては、
できるだけモレやダブりを最小限に抑えながら優先順位をつけることが、
企業の意思決定者にとって肝要となる。

＜MECE＞は網羅性を追及するための分解ツールとしては強力だが、
その先の経営資源配分の優先順位付けに失敗すれば意味がない。

### 2 フレームワークで＜MECE＞を学ぶ

::: {.message}
世の中のフレームワークの多くは＜MECE＞の応用である。
:::

#### 3C + 1C

::: {.message}
顧客（Customer）、競合（Comperitor）、自社（Company）およびチャネル（Channel）
:::
戦略は単純明快なほどいい。
なぜなら、あまり複雑だと実行が困難になるから。

#### ビジネス・システム

::: {.message}
製品・サービスが開発されてから市場に出るまでの
付加価値の流れを時間軸で＜MECE＞に整理したフレームワークを
ビジネス・システムとかバリュー・デリバリー・システムとか呼ぶ。
:::

<ゼロベース思考>で「顧客にとっての最大の価値を提供する」視点で自社のビジネスの流れを見直すと、
現状とのギャップが明確になる。


#### マーケティングの4P

::: {.message}
Product, Price, Place, Promotion
:::

#### 事業ポートフォリオ

::: {.message}
X軸に相対マーケットシェア、
Y軸に市場成長率をとって各事業をプロット\
資源配分を考えるときに使う
:::

## 1 <ロジックツリー> --- 限られた時間の中で広がりと深さを押さえる ---

ロジックツリーは以下の3つの点で優れている

- モレやダブりを未然にチェックできる
- 原因・解決策を具体的に落とし込める
- 各内容の因果関係を明らかにできる

### 1 <ロジックツリー>で原因を追及する

::: {.message}
問題を解決するときは、
根っこの具体的原因を突き止めることが重要
:::

ロジックツリーを使って、
根っこの具体的原因を突き止めるには、
とにかくWHY?を自問自答し続けることが必要。

WHY?を続けて問題を深堀すれば、
問題のの裏返しの解も通用するものになるかもしれない。

真相が解明されてきたら、
解決策具体化のためのロジックツリー
によりいろいろな解決策のオプションを考える。